services:
  go_db:
    container_name: go_db
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: go_db
    ports:
      - "5432:5432"
    volumes:
      - go_db_data:/var/lib/postgresql/data

volumes:
  go_db_data: {}
